# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog
  - override launcher: joblib

# output directory, generated dynamically on each run
run:
  dir: ${paths.log_dir}/${task_name}/runs/${version_name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
sweep:
  dir: ${paths.log_dir}/${task_name}/multiruns/${version_name}/
  subdir: ${hydra.job.num}_${hydra.job.override_dirname}

job_logging:
  handlers:
    file:
      # Incorporates fix from https://github.com/facebookresearch/hydra/pull/2242
      filename: ${hydra.runtime.output_dir}/${task_name}_${version_name}.log

launcher:
  _target_: hydra_plugins.hydra_joblib_launcher.joblib_launcher.JoblibLauncher
  n_jobs: -1  # 使用所有可用CPU核心
  prefer: processes
  verbose: 0