# @package _global_

defaults:
  - _self_
  - data: adms # choose datamodule with `test_dataloader()` for evaluation
  - model: atpn_self
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"
version_name: "debug"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
